export const ActivityAction = {
  workspaceCreated: "workspace_created",
  workspaceOpened: "workspace_opened",
  containerCreated: "container_created",
  containerUpdated: "container_updated",
  containerArchived: "container_archived",
  containerDeleted: "container_deleted",
  itemCreated: "item_created",
  itemUpdated: "item_updated",
  itemMoved: "item_moved",
  itemArchived: "item_archived",
  itemDeleted: "item_deleted",
  listCreated: "list_created",
  listItemCreated: "list_item_created",
  listItemUpdated: "list_item_updated",
  listItemCompleted: "list_item_completed",
  listItemReopened: "list_item_reopened",
  listItemReordered: "list_item_reordered",
  noteCreated: "note_created",
  noteUpdated: "note_updated",
  noteArchived: "note_archived",
  taskCreated: "task_created",
  taskUpdated: "task_updated",
  taskCompleted: "task_completed",
  taskReopened: "task_reopened",
  taskPlanned: "task_planned",
  taskUnplanned: "task_unplanned",
  taskPlanReordered: "task_plan_reordered",
  tagCreated: "tag_created",
  tagAdded: "tag_added",
  tagRemoved: "tag_removed",
  categoryCreated: "category_created",
  categoryUpdated: "category_updated",
  categoryDeleted: "category_deleted",
  categoryAssigned: "category_assigned",
  relationshipCreated: "relationship_created",
  relationshipRemoved: "relationship_removed",
  savedViewCreated: "saved_view_created",
  savedViewUpdated: "saved_view_updated",
  savedViewDeleted: "saved_view_deleted",
  fileAttached: "file_attached",
  searchIndexRebuilt: "search_index_rebuilt",
  backupCreated: "backup_created",
  exportCreated: "export_created"
} as const;

export type ActivityAction =
  (typeof ActivityAction)[keyof typeof ActivityAction];

